export const schoolsData = [
  {
    id: "1",
    name: "The Doon School",
    location: "Dehradun, Uttarakhand",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/6e618dd7-7dce-458a-b326-0e4db7d1bd39.jpg",
    fees: "13,62,000",
    rating: 4.3,
    votes: 22,
    views: 1200,
    type: "Boarding School",
    managementType: "Private",
    board: ["ICSE", "ISC", "IGCSE", "IB DP"],
    gender: "Boys School",
    grade: "7-12",
    feesRange: "Above 10 Lac",
    isAdmissionOpen: true,
    comment:
      "Established in 1935, The Doon School is a premier all-boys boarding school in Dehradun. The school follows the ICSE, IB, IGCSE, and Doon School curriculum. It offers admis...",
  },
  {
    id: "2",
    name: "Welham Girls School",
    location: "Dehradun, Uttarakhand",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/409b8d33-2252-4bd8-9750-1164276201c7.jpg",
    fees: "10,10,000",
    rating: 4.3,
    votes: 18,
    views: 950,
    type: "Boarding School",
    managementType: "Private",
    board: ["ICSE", "ISC"],
    gender: "Girls School",
    grade: "6-12",
    feesRange: "Above 7 Lac And Under 10 Lac",
    isAdmissionOpen: false,
    comment:
      "Welham Girls' School is located on the Municipal Road, Dehradun, India. This all-girls premier boarding school was founded in 1957 by H. S. Oliphant. The school is aff...",
  },
  {
    id: "3",
    name: "Rishi Valley School",
    location: "Chittoor, Andhra Pradesh",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/eb411657-c6b3-46d2-99ea-26937d4a6885.jpg",
    fees: "8,75,000",
    rating: 4.5,
    votes: 13,
    views: 740,
    type: "Boarding School",
    managementType: "Private",
    board: ["ICSE", "ISC"],
    gender: "Co-ed",
    grade: "6-12",
    feesRange: "Above 5 Lac And Under 7 Lac",
    isAdmissionOpen: true,
    comment:
      "Rishi Valley School is located in a serene valley in Andhra Pradesh. Founded by Jiddu Krishnamurti, it offers a holistic education...",
  },
  {
    id: "4",
    name: "Mayo College",
    location: "Ajmer, Rajasthan",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/65a284a6-ddab-4932-bfc1-230eb9713774.jpg",
    fees: "9,50,000",
    rating: 4.4,
    votes: 20,
    views: 890,
    type: "Boarding School",
    managementType: "Private",
    board: ["CBSE"],
    gender: "Boys School",
    grade: "4-12",
    feesRange: "Above 7 Lac And Under 10 Lac",
    isAdmissionOpen: false,
    comment:
      "Mayo College, established in 1875, is one of the oldest and most prestigious boarding schools for boys in India...",
  },
  {
    id: "5",
    name: "Kendriya Vidyalaya",
    location: "Delhi, India",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/a1d28dc7-3e11-4ca2-b6dd-7e9ab41aa417.png",
    fees: "25,000",
    rating: 4.0,
    votes: 200,
    views: 5000,
    type: "Day School",
    managementType: "Government",
    board: ["CBSE"],
    gender: "Co-ed",
    grade: "1-12",
    feesRange: "Under 1 Lac",
    isAdmissionOpen: true,
    comment:
      "Kendriya Vidyalayas are a system of central government schools under the Ministry of Education, India...",
  },
  {
    id: "6",
    name: "Jawahar Navodaya Vidyalaya",
    location: "Lucknow, Uttar Pradesh",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/3b3f5e70-ae52-4de7-bc1e-8e64aa0d7a95.jpg",
    fees: "12,000",
    rating: 4.2,
    votes: 180,
    views: 4100,
    type: "Boarding School",
    managementType: "Government",
    board: ["CBSE"],
    gender: "Co-ed",
    grade: "6-12",
    feesRange: "Under 1 Lac",
    isAdmissionOpen: false,
    comment:
      "Jawahar Navodaya Vidyalayas are co-educational residential schools fully financed by the Government of India and run by Navodaya Vidyalaya Samiti...",
  },
];
