export const schoolsData = [
  {
    id: "1",
    name: "The Doon School",
    location: "Dehradun, Uttarakhand",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/6e618dd7-7dce-458a-b326-0e4db7d1bd39.jpg",
    fees: "13,62,000",
    boardingFees: "15,00,000",
    rating: 4.3,
    votes: 22,
    views: 1200,
    type: "Boarding School",
    managementType: "Private",
    board: "ICSE, ISC, IGCSE, IB DP",
    gender: "boys", // Changed from "Boys School"
    grade: "Class 7 to Class 12",
    feesRange: "Above 10 Lac",
    isAdmissionOpen: true,
    isVerified: true,
    verificationBadge: "Premium Verified",
    comment:
      "Established in 1935, The Doon School is a premier all-boys boarding school in Dehradun. The school follows the ICSE, IB, IGCSE, and Doon School curriculum.",
    about:
      "The Doon School is one of India's most prestigious boarding schools for boys, founded in 1935. Spread over 70 acres, it offers world-class facilities and a holistic education system that focuses on academic excellence, sports, and extracurricular activities.",
    address: "Mall Road, Dehradun, Uttarakhand 248001",
    phone: "+91-135-2526400",
    email: "info@doonschool.com",
    website: "https://www.doonschool.com",
    establishmentYear: 1935,
    affiliationStatus: "PERMANENT",
    affiliationGrantYear: 1935,
    trustName: "The Doon School Society",
    totalTeachers: 100,
    pgtTeachers: 35,
    tgtTeachers: 40,
    prtTeachers: 25,
    nonTeachingStaff: 80,
    studentTeacherRatio: "8:1",
    averageClassStrength: 25,
    totalStrength: 600,
    minAdmissionAge: 12,
    entryLevelSeats: 120,
    language: "English",
    acClasses: "Yes",
    transportation: "Yes",
    swimmingPool: "Yes",
    indoorSports: "Yes",
    area: "70 acres",
    totalPlaygrounds: 5,
    playgroundArea: "20 acres",
    totalRooms: 150,
    libraries: 3,
    activityRooms: 15,
    computers: 200,
    laboratories: 10,
    auditoriums: 2,
    digitalClassrooms: 40,
    ramps: "Yes",
    wifi: "Yes",
    strongRoom: "Yes",
    gymnasium: "Yes",
    fireExtinguishers: "Yes",
    clinic: "Yes",
    examinationCenter: "Yes",
    class10Subjects:
      "ENGLISH, HINDI, MATHEMATICS, SCIENCE, SOCIAL SCIENCE, COMPUTER SCIENCE",
    class12Subjects:
      "PHYSICS, CHEMISTRY, BIOLOGY, MATHEMATICS, ECONOMICS, BUSINESS STUDIES, ACCOUNTANCY, COMPUTER SCIENCE",
    outdoorSports: [
      "Cricket",
      "Football",
      "Hockey",
      "Tennis",
      "Basketball",
      "Swimming",
      "Athletics",
    ],
    indoorSports: ["Chess", "Table Tennis", "Carrom", "Squash", "Badminton"],
    nearestAirport: {
      name: "Jolly Grant Airport",
      distance: "20 Km",
    },
    nearestRailway: {
      name: "Dehradun Railway Station",
      distance: "5 Km",
    },
    nearestBus: "Dehradun ISBT",
    nearestBank: "State Bank of India",
    admissionLink: "https://www.doonschool.com/admissions",
    admissionProcess:
      "Admission is based on entrance test and interview. Parents need to fill the online application form available on the school website.",
    reviews: [
      {
        id: 1,
        parentName: "Rajesh Kumar",
        rating: 5,
        comment:
          "Excellent school with world-class facilities. My son has developed tremendously in both academics and sports.",
        verified: true,
        date: "2023-11-15",
      },
      {
        id: 2,
        parentName: "Anil Sharma",
        rating: 4,
        comment:
          "Good infrastructure and faculty. The boarding facilities are excellent with proper care for students.",
        verified: true,
        date: "2023-10-22",
      },
    ],
    faqs: [
      {
        question: "What is the admission process for The Doon School?",
        answer:
          "Admission is based on an entrance test followed by an interview. The process begins in August for the next academic year.",
      },
      {
        question: "What is the student-teacher ratio?",
        answer:
          "The student-teacher ratio is 8:1, ensuring personalized attention for each student.",
      },
    ],
    gallery: [
      {
        id: 1,
        type: "image",
        url: "https://www.doonschool.com/gallery/doon1.jpg",
        caption: "Main Building",
      },
      {
        id: 2,
        type: "image",
        url: "https://www.doonschool.com/gallery/doon2.jpg",
        caption: "Classroom",
      },
      {
        id: 3,
        type: "image",
        url: "https://www.doonschool.com/gallery/doon3.jpg",
        caption: "Science Lab",
      },
      {
        id: 4,
        type: "video",
        url: "https://www.doonschool.com/gallery/doon-tour.mp4",
        caption: "Campus Tour",
      },
    ],
    similarSchools: [2, 3, 4],
  },
  {
    id: "2",
    name: "Welham Girls School",
    location: "Dehradun, Uttarakhand",
    image:
      "https://www.edustoke.com/assets/uploads-new/409b8d33-2252-4bd8-9750-1164276201c7.jpg",
    fees: "10,10,000",
    boardingFees: "12,00,000",
    rating: 4.3,
    votes: 18,
    views: 950,
    type: "Boarding School",
    managementType: "Private",
    board: "ICSE, ISC",
    gender: "girls", // Changed from "Girls School"
    grade: "Class 6 to Class 12",
    feesRange: "Above 7 Lac And Under 10 Lac",
    isAdmissionOpen: false,
    isVerified: true,
    verificationBadge: "Premium Verified",
    comment:
      "Welham Girls' School is located on the Municipal Road, Dehradun, India. This all-girls premier boarding school was founded in 1957 by H. S. Oliphant.",
    about:
      "Welham Girls' School is one of the most prestigious all-girls boarding schools in India. Established in 1957, it provides a nurturing environment that fosters academic excellence, leadership qualities, and holistic development.",
    address: "14, Municipal Road, Dehradun, Uttarakhand 248001",
    phone: "+91-135-2653041",
    email: "info@welhamgirls.com",
    website: "https://www.welhamgirls.com",
    establishmentYear: 1957,
    affiliationStatus: "PERMANENT",
    affiliationGrantYear: 1957,
    trustName: "Welham Girls School Trust",
    totalTeachers: 80,
    pgtTeachers: 25,
    tgtTeachers: 30,
    prtTeachers: 25,
    nonTeachingStaff: 60,
    studentTeacherRatio: "10:1",
    averageClassStrength: 20,
    totalStrength: 500,
    minAdmissionAge: 11,
    entryLevelSeats: 100,
    language: "English",
    acClasses: "Yes",
    transportation: "Yes",
    swimmingPool: "Yes",
    indoorSports: "Yes",
    area: "50 acres",
    totalPlaygrounds: 4,
    playgroundArea: "15 acres",
    totalRooms: 120,
    libraries: 2,
    activityRooms: 10,
    computers: 150,
    laboratories: 8,
    auditoriums: 1,
    digitalClassrooms: 30,
    ramps: "Yes",
    wifi: "Yes",
    strongRoom: "Yes",
    gymnasium: "Yes",
    fireExtinguishers: "Yes",
    clinic: "Yes",
    examinationCenter: "Yes",
    class10Subjects:
      "ENGLISH, HINDI, MATHEMATICS, SCIENCE, SOCIAL SCIENCE, COMPUTER APPLICATIONS",
    class12Subjects:
      "PHYSICS, CHEMISTRY, BIOLOGY, MATHEMATICS, ECONOMICS, COMMERCE, ACCOUNTANCY",
    outdoorSports: [
      "Tennis",
      "Basketball",
      "Swimming",
      "Athletics",
      "Volleyball",
    ],
    indoorSports: ["Badminton", "Table Tennis", "Chess", "Yoga"],
    nearestAirport: {
      name: "Jolly Grant Airport",
      distance: "20 Km",
    },
    nearestRailway: {
      name: "Dehradun Railway Station",
      distance: "5 Km",
    },
    nearestBus: "Dehradun ISBT",
    nearestBank: "Punjab National Bank",
    admissionLink: "https://www.welhamgirls.com/admissions",
    admissionProcess:
      "Admission is based on an entrance examination and interview. Applications are available online.",
    reviews: [
      {
        id: 1,
        parentName: "Meena Patel",
        rating: 4.5,
        comment:
          "A wonderful school for girls with excellent facilities and caring staff.",
        verified: true,
        date: "2023-12-01",
      },
      {
        id: 2,
        parentName: "Sunita Gupta",
        rating: 4,
        comment:
          "Great academic focus and extracurricular activities for my daughter.",
        verified: true,
        date: "2023-11-10",
      },
    ],
    faqs: [
      {
        question: "What is the admission process for Welham Girls School?",
        answer:
          "Admission involves an entrance test and interview, typically held in November.",
      },
      {
        question: "Are there boarding facilities available?",
        answer:
          "Yes, Welham Girls School offers full boarding facilities for students.",
      },
    ],
    gallery: [
      {
        id: 1,
        type: "image",
        url: "https://www.edustoke.com/assets/uploads-new/409b8d33-2252-4bd8-9750-1164276201c7.jpg",
        caption: "Main Building",
      },
      {
        id: 2,
        type: "image",
        url: "https://www.edustoke.com/assets/uploads-new/05376670-0c5a-463d-a4df-1af4092071fc.jpg",
        caption: "Library",
      },
      {
        id: 3,
        type: "video",
        url: "https://www.welhamgirls.com/gallery/welham-tour.mp4",
        caption: "Campus Tour",
      },
      {
        id: 4,
        type: "image",
        url: "https://www.edustoke.com/assets/uploads-new/5eb7fbfd-864d-4068-abf1-f46492fd2212.jpg",
        caption: "Campus",
      },
    ],
    similarSchools: [1, 3],
  },
  {
    id: "3",
    name: "Rishi Valley School",
    location: "Chittoor, Andhra Pradesh",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/eb411657-c6b3-46d2-99ea-26937d4a6885.jpg",
    fees: "8,75,000",
    boardingFees: "10,50,000",
    rating: 4.5,
    votes: 13,
    views: 740,
    type: "Boarding School",
    managementType: "Private",
    board: "ICSE, ISC",
    gender: "co-ed", // Already correct
    grade: "Class 6 to Class 12",
    feesRange: "Above 5 Lac And Under 7 Lac",
    isAdmissionOpen: true,
    isVerified: true,
    verificationBadge: "Standard Verified",
    comment:
      "Rishi Valley School is located in a serene valley in Andhra Pradesh. Founded by Jiddu Krishnamurti, it offers a holistic education.",
    about:
      "Rishi Valley School, founded by philosopher Jiddu Krishnamurti, is known for its alternative education approach set in a beautiful natural environment. The school emphasizes holistic learning and environmental consciousness.",
    address:
      "Rishi Valley, Madanapalle, Chittoor District, Andhra Pradesh 517352",
    phone: "+91-8571-280522",
    email: "info@rishivalley.org",
    website: "https://www.rishivalley.org",
    establishmentYear: 1926,
    affiliationStatus: "PERMANENT",
    affiliationGrantYear: 1926,
    trustName: "Rishi Valley Education Centre",
    totalTeachers: 70,
    pgtTeachers: 20,
    tgtTeachers: 25,
    prtTeachers: 25,
    nonTeachingStaff: 50,
    studentTeacherRatio: "9:1",
    averageClassStrength: 20,
    totalStrength: 450,
    minAdmissionAge: 11,
    entryLevelSeats: 90,
    language: "English",
    acClasses: "No",
    transportation: "Yes",
    swimmingPool: "No",
    indoorSports: "Yes",
    area: "60 acres",
    totalPlaygrounds: 3,
    playgroundArea: "10 acres",
    totalRooms: 100,
    libraries: 2,
    activityRooms: 8,
    computers: 120,
    laboratories: 6,
    auditoriums: 1,
    digitalClassrooms: 20,
    ramps: "Yes",
    wifi: "Yes",
    strongRoom: "Yes",
    gymnasium: "No",
    fireExtinguishers: "Yes",
    clinic: "Yes",
    examinationCenter: "Yes",
    class10Subjects:
      "ENGLISH, HINDI, MATHEMATICS, SCIENCE, SOCIAL SCIENCE, ENVIRONMENTAL EDUCATION",
    class12Subjects:
      "PHYSICS, CHEMISTRY, BIOLOGY, MATHEMATICS, HISTORY, GEOGRAPHY, ECONOMICS",
    outdoorSports: [
      "Cricket",
      "Football",
      "Basketball",
      "Tennis",
      "Volleyball",
    ],
    indoorSports: ["Table Tennis", "Chess", "Carrom"],
    nearestAirport: {
      name: "Tirupati Airport",
      distance: "150 Km",
    },
    nearestRailway: {
      name: "Madanapalle Road Railway Station",
      distance: "30 Km",
    },
    nearestBus: "Madanapalle Bus Stand",
    nearestBank: "HDFC Bank",
    admissionLink: "https://www.rishivalley.org/admissions",
    admissionProcess:
      "Admission is based on an entrance exam and interview conducted in January.",
    reviews: [
      {
        id: 1,
        parentName: "Suresh Reddy",
        rating: 4.5,
        comment:
          "A unique educational experience with a focus on nature and personal growth.",
        verified: true,
        date: "2023-12-05",
      },
    ],
    faqs: [
      {
        question: "What is the admission process for Rishi Valley School?",
        answer:
          "Admission involves an entrance exam and interview held annually in January.",
      },
      {
        question: "Is the school co-educational?",
        answer: "Yes, Rishi Valley School is a co-educational institution.",
      },
    ],
    gallery: [
      {
        id: 1,
        type: "image",
        url: "https://www.rishivalley.org/gallery/rishi1.jpg",
        caption: "Valley View",
      },
      {
        id: 2,
        type: "image",
        url: "https://www.rishivalley.org/gallery/rishi2.jpg",
        caption: "Classroom",
      },
    ],
    similarSchools: [1, 2],
  },
  {
    id: "4",
    name: "Mayo College",
    location: "Ajmer, Rajasthan",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/65a284a6-ddab-4932-bfc1-230eb9713774.jpg",
    fees: "9,50,000",
    boardingFees: "11,00,000",
    rating: 4.4,
    votes: 20,
    views: 890,
    type: "Boarding School",
    managementType: "Private",
    board: "CBSE",
    gender: "boys", // Changed from "Boys School"
    grade: "Class 4 to Class 12",
    feesRange: "Above 7 Lac And Under 10 Lac",
    isAdmissionOpen: false,
    isVerified: true,
    verificationBadge: "Premium Verified",
    comment:
      "Mayo College, established in 1875, is one of the oldest and most prestigious boarding schools for boys in India.",
    about:
      "Mayo College, founded in 1875, is one of India's oldest and most prestigious boarding schools for boys. Known as 'The Eton of the East', it combines traditional values with modern education.",
    address: "Mayo College General, Ajmer, Rajasthan 305001",
    phone: "+91-145-2660990",
    email: "info@mayocollege.com",
    website: "https://www.mayocollege.com",
    establishmentYear: 1875,
    affiliationStatus: "PERMANENT",
    affiliationGrantYear: 1875,
    trustName: "Mayo College Trust",
    totalTeachers: 90,
    pgtTeachers: 30,
    tgtTeachers: 35,
    prtTeachers: 25,
    nonTeachingStaff: 70,
    studentTeacherRatio: "9:1",
    averageClassStrength: 25,
    totalStrength: 550,
    minAdmissionAge: 9,
    entryLevelSeats: 110,
    language: "English",
    acClasses: "Yes",
    transportation: "Yes",
    swimmingPool: "Yes",
    indoorSports: "Yes",
    area: "65 acres",
    totalPlaygrounds: 6,
    playgroundArea: "25 acres",
    totalRooms: 140,
    libraries: 2,
    activityRooms: 12,
    computers: 180,
    laboratories: 9,
    auditoriums: 2,
    digitalClassrooms: 35,
    ramps: "Yes",
    wifi: "Yes",
    strongRoom: "Yes",
    gymnasium: "Yes",
    fireExtinguishers: "Yes",
    clinic: "Yes",
    examinationCenter: "Yes",
    class10Subjects:
      "ENGLISH, HINDI, MATHEMATICS, SCIENCE, SOCIAL SCIENCE, COMPUTER APPLICATIONS",
    class12Subjects:
      "PHYSICS, CHEMISTRY, BIOLOGY, MATHEMATICS, ECONOMICS, BUSINESS STUDIES, ACCOUNTANCY",
    outdoorSports: [
      "Polo",
      "Cricket",
      "Hockey",
      "Tennis",
      "Swimming",
      "Shooting",
    ],
    indoorSports: ["Squash", "Badminton", "Table Tennis", "Chess"],
    nearestAirport: {
      name: "Jaipur International Airport",
      distance: "135 Km",
    },
    nearestRailway: {
      name: "Ajmer Junction",
      distance: "5 Km",
    },
    nearestBus: "Ajmer Bus Stand",
    nearestBank: "Bank of Baroda",
    admissionLink: "https://www.mayocollege.com/admissions",
    admissionProcess:
      "Admission is based on an entrance test and interview, typically in November.",
    reviews: [
      {
        id: 1,
        parentName: "Vikram Singh",
        rating: 4.5,
        comment:
          "A historic school with excellent sports facilities and traditions.",
        verified: true,
        date: "2023-11-20",
      },
      {
        id: 2,
        parentName: "Rakesh Mehta",
        rating: 4,
        comment:
          "Great academic support and a rich cultural environment for boys.",
        verified: true,
        date: "2023-10-15",
      },
    ],
    faqs: [
      {
        question: "What is the admission process for Mayo College?",
        answer:
          "Admission involves an entrance exam and interview, held annually in November.",
      },
      {
        question: "Does the school offer boarding facilities?",
        answer: "Yes, Mayo College provides full boarding facilities.",
      },
    ],
    gallery: [
      {
        id: 1,
        type: "image",
        url: "https://www.mayocollege.com/gallery/mayo1.jpg",
        caption: "Main Campus",
      },
      {
        id: 2,
        type: "image",
        url: "https://www.mayocollege.com/gallery/mayo2.jpg",
        caption: "Sports Field",
      },
      {
        id: 3,
        type: "video",
        url: "https://www.mayocollege.com/gallery/mayo-tour.mp4",
        caption: "Campus Tour",
      },
    ],
    similarSchools: [1, 2],
  },
  {
    id: "5",
    name: "Kendriya Vidyalaya",
    location: "Delhi, India",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/a1d28dc7-3e11-4ca2-b6dd-7e9ab41aa417.png",
    fees: "25,000",
    rating: 4.0,
    votes: 200,
    views: 5000,
    type: "Day School",
    managementType: "Government",
    board: "CBSE",
    gender: "co-ed", // Already correct
    grade: "Class 1 to Class 12",
    feesRange: "Under 1 Lac",
    isAdmissionOpen: true,
    isVerified: false,
    comment:
      "Kendriya Vidyalayas are a system of central government schools under the Ministry of Education, India.",
    about:
      "Kendriya Vidyalayas are a system of central government schools under the Ministry of Education, Government of India. They are known for providing quality education at affordable fees with a uniform curriculum across India.",
    address: "Various locations across India",
    phone: "+91-11-26172627",
    email: "feedback@kvsangathan.nic.in",
    website: "https://kvsangathan.nic.in",
    establishmentYear: 1963,
    affiliationStatus: "PERMANENT",
    affiliationGrantYear: 1963,
    trustName: "Kendriya Vidyalaya Sangathan",
    totalTeachers: 150,
    pgtTeachers: 50,
    tgtTeachers: 60,
    prtTeachers: 40,
    nonTeachingStaff: 100,
    studentTeacherRatio: "20:1",
    averageClassStrength: 40,
    totalStrength: 2000,
    minAdmissionAge: 5,
    entryLevelSeats: 200,
    language: "English, Hindi",
    acClasses: "No",
    transportation: "Yes",
    swimmingPool: "No",
    indoorSports: "Yes",
    area: "10 acres",
    totalPlaygrounds: 2,
    playgroundArea: "5 acres",
    totalRooms: 50,
    libraries: 1,
    activityRooms: 5,
    computers: 100,
    laboratories: 4,
    auditoriums: 1,
    digitalClassrooms: 10,
    ramps: "Yes",
    wifi: "Yes",
    strongRoom: "Yes",
    gymnasium: "No",
    fireExtinguishers: "Yes",
    clinic: "Yes",
    examinationCenter: "Yes",
    class10Subjects:
      "ENGLISH, HINDI, MATHEMATICS, SCIENCE, SOCIAL SCIENCE, INFORMATION TECHNOLOGY",
    class12Subjects:
      "PHYSICS, CHEMISTRY, BIOLOGY, MATHEMATICS, ECONOMICS, HISTORY, GEOGRAPHY",
    outdoorSports: [
      "Cricket",
      "Football",
      "Basketball",
      "Volleyball",
      "Athletics",
    ],
    indoorSports: ["Table Tennis", "Chess", "Carrom", "Yoga"],
    nearestAirport: {
      name: "Indira Gandhi International Airport",
      distance: "15 Km",
    },
    nearestRailway: {
      name: "New Delhi Railway Station",
      distance: "5 Km",
    },
    nearestBus: "ISBT Kashmiri Gate",
    nearestBank: "State Bank of India",
    admissionLink: "https://kvsangathan.nic.in/admissions",
    admissionProcess:
      "Admission is based on an online application and lottery system for certain classes.",
    reviews: [
      {
        id: 1,
        parentName: "Amit Verma",
        rating: 4,
        comment:
          "Affordable and quality education with good teachers and facilities.",
        verified: true,
        date: "2023-11-25",
      },
      {
        id: 2,
        parentName: "Priya Sharma",
        rating: 3.5,
        comment:
          "Good school, but infrastructure needs improvement in some areas.",
        verified: true,
        date: "2023-10-30",
      },
    ],
    faqs: [
      {
        question: "What is the admission process for Kendriya Vidyalaya?",
        answer:
          "Admission is based on an online application and lottery system for eligible candidates.",
      },
      {
        question: "Is there a fee for admission?",
        answer:
          "There is a nominal admission fee, and education is largely subsidized by the government.",
      },
    ],
    gallery: [
      {
        id: 1,
        type: "image",
        url: "https://kvsangathan.nic.in/gallery/kv1.jpg",
        caption: "School Building",
      },
      {
        id: 2,
        type: "image",
        url: "https://kvsangathan.nic.in/gallery/kv2.jpg",
        caption: "Playground",
      },
    ],
    similarSchools: [6],
  },
  {
    id: "6",
    name: "Jawahar Navodaya Vidyalaya",
    location: "Lucknow, Uttar Pradesh",
    image:
      "https://www.edustoke.com/assets/uploads-new/thumbs-resize/3b3f5e70-ae52-4de7-bc1e-8e64aa0d7a95.jpg",
    fees: "12,000",
    rating: 4.2,
    votes: 180,
    views: 4100,
    type: "Boarding School",
    managementType: "Government",
    board: "CBSE",
    gender: "co-ed", // Already correct
    grade: "Class 6 to Class 12",
    feesRange: "Under 1 Lac",
    isAdmissionOpen: false,
    isVerified: true,
    verificationBadge: "Government Verified",
    comment:
      "Jawahar Navodaya Vidyalayas are co-educational residential schools fully financed by the Government of India.",
    about:
      "Jawahar Navodaya Vidyalayas are co-educational residential schools fully financed by the Government of India. They aim to provide quality education to talented children predominantly from rural areas.",
    address: "Various locations across India",
    phone: "+91-11-26565678",
    email: "contact@navodaya.gov.in",
    website: "https://navodaya.gov.in",
    establishmentYear: 1986,
    affiliationStatus: "PERMANENT",
    affiliationGrantYear: 1986,
    trustName: "Navodaya Vidyalaya Samiti",
    totalTeachers: 120,
    pgtTeachers: 40,
    tgtTeachers: 50,
    prtTeachers: 30,
    nonTeachingStaff: 90,
    studentTeacherRatio: "15:1",
    averageClassStrength: 35,
    totalStrength: 1500,
    minAdmissionAge: 9,
    entryLevelSeats: 160,
    language: "English, Hindi",
    acClasses: "No",
    transportation: "Yes",
    swimmingPool: "No",
    indoorSports: "Yes",
    area: "15 acres",
    totalPlaygrounds: 2,
    playgroundArea: "5 acres",
    totalRooms: 60,
    libraries: 1,
    activityRooms: 4,
    computers: 80,
    laboratories: 3,
    auditoriums: 1,
    digitalClassrooms: 8,
    ramps: "Yes",
    wifi: "Yes",
    strongRoom: "Yes",
    gymnasium: "No",
    fireExtinguishers: "Yes",
    clinic: "Yes",
    examinationCenter: "Yes",
    class10Subjects:
      "ENGLISH, HINDI, MATHEMATICS, SCIENCE, SOCIAL SCIENCE, WORK EXPERIENCE",
    class12Subjects:
      "PHYSICS, CHEMISTRY, BIOLOGY, MATHEMATICS, ECONOMICS, HISTORY, GEOGRAPHY",
    outdoorSports: [
      "Cricket",
      "Football",
      "Volleyball",
      "Athletics",
      "Kho-Kho",
    ],
    indoorSports: ["Table Tennis", "Chess", "Carrom", "Yoga"],
    nearestAirport: {
      name: "Chaudhary Charan Singh Airport",
      distance: "15 Km",
    },
    nearestRailway: {
      name: "Lucknow Charbagh Railway Station",
      distance: "5 Km",
    },
    nearestBus: "Lucknow Bus Stand",
    nearestBank: "Bank of India",
    admissionLink: "https://navodaya.gov.in/admissions",
    admissionProcess:
      "Admission is based on a national-level entrance exam conducted annually.",
    reviews: [
      {
        id: 1,
        parentName: "Deepak Yadav",
        rating: 4.5,
        comment:
          "Great opportunity for rural students with excellent teaching staff.",
        verified: true,
        date: "2023-11-18",
      },
      {
        id: 2,
        parentName: "Neha Singh",
        rating: 4,
        comment:
          "Good facilities and supportive environment for my child's growth.",
        verified: true,
        date: "2023-10-12",
      },
    ],
    faqs: [
      {
        question: "What is the admission process for JNV?",
        answer:
          "Admission is through a national-level entrance exam held in February.",
      },
      {
        question: "Is boarding free?",
        answer:
          "Yes, boarding and lodging are free for students, with a nominal fee for others.",
      },
    ],
    gallery: [
      {
        id: 1,
        type: "image",
        url: "https://navodaya.gov.in/gallery/jnv1.jpg",
        caption: "School Campus",
      },
      {
        id: 2,
        type: "image",
        url: "https://navodaya.gov.in/gallery/jnv2.jpg",
        caption: "Classroom",
      },
    ],
    similarSchools: [5],
  },
];
