import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import BottomNav from "./components/BottomNav";
import Navbar from "./components/Navbar";
import SubNavbar from "./components/Subnav";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // you can add/remove weights as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
        style={{ fontFamily: "var(--font-poppins), sans-serif" }}
        cz-shortcut-listen="true"
      >
        <Navbar />
        <div className="pt-14 sm:pt-16">
          <SubNavbar />
        </div>
        {children}
        <Footer />
        <BottomNav />
      </body>
    </html>
  );
}
